// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Login agora recebe o apiBaseURL como parâmetro
func Login(apiBaseURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"en-US\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>FinSync - Login</title><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-[#F3F4F6] text-[#1E3A8A] font-sans\"><div class=\"min-h-screen flex justify-center items-center\"><div class=\"bg-white p-8 rounded-xl shadow-md w-full max-w-sm\"><div class=\"flex justify-center mb-6\"><img src=\"./static/images/logo-finsync.png\" alt=\"Logo FinSync\" class=\"h-48 w-auto\"></div><h2 class=\"text-2xl font-bold text-center mb-2\">Access Your FinAccount</h2><form id=\"login-form\" class=\"space-y-5\"><div><label for=\"email\" class=\"block mb-1 font-medium\">E‑mail</label> <input type=\"email\" id=\"email\" name=\"email\" class=\"w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#1E3A8A]\" placeholder=\"you@example.com\" required></div><div><label for=\"password\" class=\"block mb-1 font-medium\">Password</label> <input type=\"password\" id=\"password\" name=\"password\" class=\"w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#1E3A8A]\" placeholder=\"••••••••\" required></div><button type=\"submit\" class=\"w-full bg-[#1E3A8A] hover:bg-[#1e40af] text-white p-3 rounded-md font-semibold transition\">Login</button></form><div id=\"error-message\" class=\"text-[#EF4444] text-sm text-center mt-4 hidden\">An error occurred during login. Please check your credentials.</div><p class=\"text-center mt-6 text-sm text-[#374151]\">Don't have an account? <a href=\"/register\" class=\"text-[#1E3A8A] font-semibold hover:underline\">Signup here</a></p></div></div><script>\n    const API_BASE = \"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2, templ_7745c5c3_Err := templruntime.ScriptContentInsideStringLiteral(apiBaseURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/views/login.templ`, Line: 48, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\";\n\n    document.getElementById('login-form').addEventListener('submit', async function (e) {\n        e.preventDefault();\n        const email = document.getElementById('email').value;\n        const password = document.getElementById('password').value;\n\n        const response = await fetch(`${API_BASE}/api/login`, {\n            method: 'POST',\n            headers: { 'Content-Type': 'application/json' },\n            body: JSON.stringify({ email, password }),\n            credentials: 'include'\n        });\n\n        if (response.ok) {\n            window.location.href = '/dashboard';\n        } else {\n            document.getElementById('error-message').classList.remove('hidden');\n        }\n    });\n</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
