// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/gabrielksneiva/go-financial-transactions/domain"
	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// GetByUser provides a mock function with given fields: userID
func (_m *TransactionRepository) GetByUser(userID uint) ([]domain.Transaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Transaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type TransactionRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - userID uint
func (_e *TransactionRepository_Expecter) GetByUser(userID interface{}) *TransactionRepository_GetByUser_Call {
	return &TransactionRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", userID)}
}

func (_c *TransactionRepository_GetByUser_Call) Run(run func(userID uint)) *TransactionRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *TransactionRepository_GetByUser_Call) Return(_a0 []domain.Transaction, _a1 error) *TransactionRepository_GetByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_GetByUser_Call) RunAndReturn(run func(uint) ([]domain.Transaction, error)) *TransactionRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: tx
func (_m *TransactionRepository) Save(tx domain.Transaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Transaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TransactionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - tx domain.Transaction
func (_e *TransactionRepository_Expecter) Save(tx interface{}) *TransactionRepository_Save_Call {
	return &TransactionRepository_Save_Call{Call: _e.mock.On("Save", tx)}
}

func (_c *TransactionRepository_Save_Call) Run(run func(tx domain.Transaction)) *TransactionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Save_Call) Return(_a0 error) *TransactionRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Save_Call) RunAndReturn(run func(domain.Transaction) error) *TransactionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
