// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "github.com/gabrielksneiva/go-financial-transactions/domain"
	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

type TransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRepository) EXPECT() *TransactionRepository_Expecter {
	return &TransactionRepository_Expecter{mock: &_m.Mock}
}

// GetByUser provides a mock function with given fields: userID
func (_m *TransactionRepository) GetByUser(userID uint) ([]domain.Transaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Transaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type TransactionRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - userID uint
func (_e *TransactionRepository_Expecter) GetByUser(userID interface{}) *TransactionRepository_GetByUser_Call {
	return &TransactionRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", userID)}
}

func (_c *TransactionRepository_GetByUser_Call) Run(run func(userID uint)) *TransactionRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *TransactionRepository_GetByUser_Call) Return(_a0 []domain.Transaction, _a1 error) *TransactionRepository_GetByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_GetByUser_Call) RunAndReturn(run func(uint) ([]domain.Transaction, error)) *TransactionRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionsByUserID provides a mock function with given fields: userID
func (_m *TransactionRepository) GetTransactionsByUserID(userID uint) ([]domain.Transaction, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByUserID")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]domain.Transaction, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []domain.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionRepository_GetTransactionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsByUserID'
type TransactionRepository_GetTransactionsByUserID_Call struct {
	*mock.Call
}

// GetTransactionsByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *TransactionRepository_Expecter) GetTransactionsByUserID(userID interface{}) *TransactionRepository_GetTransactionsByUserID_Call {
	return &TransactionRepository_GetTransactionsByUserID_Call{Call: _e.mock.On("GetTransactionsByUserID", userID)}
}

func (_c *TransactionRepository_GetTransactionsByUserID_Call) Run(run func(userID uint)) *TransactionRepository_GetTransactionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *TransactionRepository_GetTransactionsByUserID_Call) Return(_a0 []domain.Transaction, _a1 error) *TransactionRepository_GetTransactionsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionRepository_GetTransactionsByUserID_Call) RunAndReturn(run func(uint) ([]domain.Transaction, error)) *TransactionRepository_GetTransactionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: tx
func (_m *TransactionRepository) Save(tx domain.Transaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Transaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TransactionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - tx domain.Transaction
func (_e *TransactionRepository_Expecter) Save(tx interface{}) *TransactionRepository_Save_Call {
	return &TransactionRepository_Save_Call{Call: _e.mock.On("Save", tx)}
}

func (_c *TransactionRepository_Save_Call) Run(run func(tx domain.Transaction)) *TransactionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Transaction))
	})
	return _c
}

func (_c *TransactionRepository_Save_Call) Return(_a0 error) *TransactionRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_Save_Call) RunAndReturn(run func(domain.Transaction) error) *TransactionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransactionHash provides a mock function with given fields: txID, txHash
func (_m *TransactionRepository) UpdateTransactionHash(txID string, txHash string) error {
	ret := _m.Called(txID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(txID, txHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_UpdateTransactionHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransactionHash'
type TransactionRepository_UpdateTransactionHash_Call struct {
	*mock.Call
}

// UpdateTransactionHash is a helper method to define mock.On call
//   - txID string
//   - txHash string
func (_e *TransactionRepository_Expecter) UpdateTransactionHash(txID interface{}, txHash interface{}) *TransactionRepository_UpdateTransactionHash_Call {
	return &TransactionRepository_UpdateTransactionHash_Call{Call: _e.mock.On("UpdateTransactionHash", txID, txHash)}
}

func (_c *TransactionRepository_UpdateTransactionHash_Call) Run(run func(txID string, txHash string)) *TransactionRepository_UpdateTransactionHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TransactionRepository_UpdateTransactionHash_Call) Return(_a0 error) *TransactionRepository_UpdateTransactionHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_UpdateTransactionHash_Call) RunAndReturn(run func(string, string) error) *TransactionRepository_UpdateTransactionHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransactionStatus provides a mock function with given fields: txID, status
func (_m *TransactionRepository) UpdateTransactionStatus(txID string, status string) error {
	ret := _m.Called(txID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransactionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(txID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRepository_UpdateTransactionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransactionStatus'
type TransactionRepository_UpdateTransactionStatus_Call struct {
	*mock.Call
}

// UpdateTransactionStatus is a helper method to define mock.On call
//   - txID string
//   - status string
func (_e *TransactionRepository_Expecter) UpdateTransactionStatus(txID interface{}, status interface{}) *TransactionRepository_UpdateTransactionStatus_Call {
	return &TransactionRepository_UpdateTransactionStatus_Call{Call: _e.mock.On("UpdateTransactionStatus", txID, status)}
}

func (_c *TransactionRepository_UpdateTransactionStatus_Call) Run(run func(txID string, status string)) *TransactionRepository_UpdateTransactionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TransactionRepository_UpdateTransactionStatus_Call) Return(_a0 error) *TransactionRepository_UpdateTransactionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRepository_UpdateTransactionStatus_Call) RunAndReturn(run func(string, string) error) *TransactionRepository_UpdateTransactionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
